import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [data, setData] = useState(null)
  const [isLoading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true)
    fetch('https://jsonplaceholder.typicode.com/users')
      .then(res => res.json())
      .then(data => {
        setData(data)
        setLoading(false)
      })
  }, [])

  // handle ketika loading
  if (isLoading) return <p>Loading...</p>
  // handle ketika data kosong
  if (!data) return <p>No profile data</p>

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>With useEffect</h1>
      <Link href="/swr">Dengan SWR</Link>
      <div className={styles.grid}>
        {data &&
          data.map(user => (
            <div key={user.id} className={styles.card}>
              <p className={styles.title}>{user.name}</p>
            </div>
          ))}
      </div>
    </div>
  )
}
